export const IPCKeys = {
  GQL: "GQL",

  LOG_FATAL: "LOG_FATAL",
  LOG_ERROR: "LOG_ERROR",
  LOG_WARN: "LOG_WARN",
  LOG_INFO: "LOG_INFO",
  LOG_DEBUG: "LOG_DEBUG",
  LOG_TRACE: "LOG_TRACE",

  FS_BROWSE: "FS_BROWSE",
  FS_READ: "FS_READ",
  FS_WRITE: "FS_WRITE",
  FS_GET_SUBDIR: "FS_GET_SUBDIR",
  FS_GET_TREE: "FS_GET_TREE",
  FS_EXIST: "FS_EXIST",
  FS_MKDIR: "FS_MKDIR",
  FS_UNZIP: "FS_UNZIP",

  WEB_OPEN: "WEB_OPEN",
  WEB_FETCH: "WEB_FETCH",
  WEB_CLONE: "WEB_CLONE",
  WEB_DL: "WEB_DL",

  GITHUB_FETCH: "GITHUB_FETCH",
  GITHUB_CLONE: "GITHUB_CLONE", // TODO

  RUN_EXECA: "RUN_EXECA",

  SYS_HOME: "SYS_HOME",
  SYS_HIDDEN: "SYS_HIDDEN",
  SYS_COPY: "SYS_COPY",

  CONFIG_GET_COLOR: "CONFIG_GET_COLOR",
  CONFIG_SET_COLOR: "CONFIG_SET_COLOR",
  CONFIG_GET_RECENT: "CONFIG_GET_RECENT",
  CONFIG_SET_RECENT: "CONFIG_SET_RECENT",
} as const;
